# Generated by Django 2.2 on 2019-08-09 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodmenu', '0012_auto_20190808_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodmenu',
            name='smallimg',
        ),
    ]
