# Generated by Django 2.2 on 2019-08-09 15:57

from django.db import migrations
import goodmenu.fields


class Migration(migrations.Migration):

    dependencies = [
        ('goodmenu', '0013_remove_goodmenu_smallimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodmenu',
            name='smallimg',
            field=goodmenu.fields.ThumbnailImageField(null=True, upload_to='goodmenu/%Y/%m'),
        ),
    ]
